version: 0.2
phases:
  install:
    commands:
      - npm install
      - npm install -g mocha
      - npm install -g serverless@1.23.0
  build:
    commands:
      - serverless deploy --stage ${TARGET_STAGE}
  post_build:
    commands:
      - HELLO_API_ENDPOINT="$(serverless info --stage ${TARGET_STAGE} -v | grep ServiceEndpoint | awk '{ print $2; }')" mocha
      - serverless remove --stage ${TARGET_STAGE}
